on:
  push:
    branches: [master]
    paths-ignore:
      - "**/README.md"

name: Test, Build and Release apk
jobs:
  build:
    name: Build apk & ipa
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.5"
          channel: "stable"
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      # - run: flutter build ios --no-codesign
      - uses: actions/upload-artifact@v3
        with:
          path: "build/app/outputs/apk/release/*.apk"
